[global]
showWarningOnDirectExecution = true

[logger]
level = "info"

[client]
showErrorDetails = true

[server]
enableCORS = false
enableXsrfProtection = false
port = 8501
baseUrlPath = ""
enableWebsocketCompression = false

[browser]
serverAddress = "localhost"
serverPort = 8501
